apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: services
    namespace: argocd
spec:
    description: 'Root application project for managing infra-services components'
    sourceRepos:
        - '*'
    destinations:
        - server: 'https://kubernetes.default.svc'
          namespace: '*'
        - server: '*'
          namespace: '*'
    clusterResourceWhitelist:
        - group: '*'
          kind: '*'
