apiVersion: v1
kind: ConfigMap
metadata:
    name: application-config
    namespace: argocd
data:
    SPLIT_SERVICE_URL: http://split-service:5000/api/split
    FRAGMENTS_COUNT: '6'
    BUCKET_NAME: sobel
    REDIS_PORT: '6379'
    REDIS_HOST: redis-master.redis-namespace.svc.cluster.local
