apiVersion: v1
kind: ConfigMap
metadata:
    name: application-config
data:
    SPLIT_SERVICE_URL: http://split-service:5000/api/split
    FRAGMENTS_COUNT: '4'
    BUCKET_NAME: sobel
    REDIS_PORT: '6379'
    REDIS_HOST: redis-master
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: redis-master
data:
    redis.conf: |
        appendonly no
        protected-mode no
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: redis-replica
data:
    redis.conf: |+
        replicaof redis-master 6379
