apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app: redis
    template:
        metadata:
            labels:
                app: redis
        spec:
            containers:
                - name: redis
                  image: redis:alpine3.19
                  command:
                      - redis-server
                  ports:
                      - containerPort: 6379
                  volumeMounts:
                      - mountPath: /data
                        name: redis-volume
            volumes:
                - name: redis-volume
                  persistentVolumeClaim:
                      claimName: redis-data
