apiVersion: apps/v1
kind: Deployment
metadata:
    name: split-service
spec:
    replicas: 3
    selector:
        matchLabels:
            app: split-service
    template:
        metadata:
            labels:
                app: split-service
        spec:
            containers:
                - name: split-service
                  image: 'fedesin31/split-service:latest'
                  ports:
                      - containerPort: 5000
                  env:
                      - name: FRAGMENTS_COUNT
                        valueFrom:
                            configMapKeyRef:
                                name: application-config
                                key: FRAGMENTS_COUNT
                      - name: BUCKET_NAME
                        valueFrom:
                            configMapKeyRef:
                                name: application-config
                                key: BUCKET_NAME
                      - name: REDIS_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: application-config
                                key: REDIS_HOST
                      - name: REDIS_PORT
                        valueFrom:
                            configMapKeyRef:
                                name: application-config
                                key: REDIS_PORT
                      - name: RABBITMQ_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: rabbit-config
                                key: RABBITMQ_HOST
                      - name: RABBITMQ_USER
                        valueFrom:
                            configMapKeyRef:
                                name: rabbit-config
                                key: RABBITMQ_USER
                      - name: RABBITMQ_PASSWORD
                        valueFrom:
                            configMapKeyRef:
                                name: rabbit-config
                                key: RABBITMQ_PASSWORD
                      - name: CREDENTIALS_PATH
                        value: /credentials/credentials.json
                  volumeMounts:
                      - name: credentials-volume
                        mountPath: /credentials
                        readOnly: true
            volumes:
                - name: credentials-volume
                  configMap:
                      name: credentials-config
            # Agrega toleration para asegurar que los pods se creen unicamente en el node group de aplicaciones
            tolerations:
                - key: instance_type
                  operator: Equal
                  value: applications
                  effect: NoSchedule
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                  - key: role
                                    operator: In
                                    values:
                                        - applications
