apiVersion: v1
kind: ConfigMap
metadata:
    name: redis-master
    namespace: argocd
data:
    redis.conf: |
        appendonly no
        protected-mode no
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: redis-replica
    namespace: redis-namespace
data:
    redis.conf: |+
        replicaof redis-master 6379
