apiVersion: v1
kind: Service
metadata:
    name: entry-server
spec:
    type: LoadBalancer
    selector:
        app: entry-server
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
