apiVersion: v1
kind: Service
metadata:
    name: join-service
spec:
    type: ClusterIP
    selector:
        app: join-service
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000
