name: Applications pipeline

on:
    push:
        branches: ['main']
jobs:
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./sobel-service
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sobel-service:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./split-service
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/split-service:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./entry-server
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/entry-server:latest

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./join-service
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/join-service:latest
