name: Workers pipeline

on:
    push:
        branches: ['main']
jobs:
    build-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Copy credentials.json
              run: |
                  echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > sobel-service/credentials.json
                  ls -la sobel-service

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./sobel-service
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/sobel-service:latest
    infra-up:
        name: Build workers infrastructure
        if: startsWith(github.event.head_commit.message, '(workers-up)')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

              # Configuración CLI Google Cloud.
            - name: Google Cloud authentication
              uses: google-github-actions/auth@v1
              with:
                  credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}

            - name: Google Cloud kubectl plugin
              uses: google-github-actions/setup-gcloud@v1
              with:
                  version: '>= 363.0.0'
                  install_components: 'kubectl'

            - name: Google Cloud kubectl cluster metadata
              run: |
                  gcloud info
                  gcloud components list
                  gcloud container clusters get-credentials primary --region=us-east1-b

            # Setup de CLI de Terraform
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2

            # Crea el cluster en la nube.
            - name: Terraform init
              working-directory: terraform
              env:
                  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
              run: |
                  RABBIT_SERVICE_IP=$(kubectl get svc rabbitmq -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
                  RABBITMQ_PASSWORD=$(kubectl get secret rabbitmq-default-user -o jsonpath="{.data.password}" | base64 --decode)
                  RABBITMQ_USER=$(kubectl get secret rabbitmq-default-user -o jsonpath="{.data.username}" | base64 --decode)

                  echo "Service IP: $RABBIT_SERVICE_IP"
                  echo "Rabbit user: $RABBITMQ_PASSWORD"
                  echo "Rabbit password: $RABBITMQ_USER"

                  echo -e 'sudo docker run -p 80:5000 \
                    --name sobel \
                    -e BUCKET_NAME="sobel" \
                    -e RABBITMQ_HOST=${RABBITMQ_HOST} \
                    -e RABBITMQ_USER=${RABBITMQ_USER} \
                    -e RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD} \
                    -e CREDENTIALS_PATH=/sobel/credentials/credentials.json \
                    mgimenezdev/sobel-service:latest' > ./scripts/init.sh

                  echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > credentials.json

                  ls -lah

                  bucket_name="terraform_state_cloud"
                  prefix="workers/state"

                  terraform init --reconfigure \
                    --backend-config "bucket=${bucket_name}" \
                    --backend-config "prefix=${prefix}"

                  terraform validate

                  terraform plan -lock=false

                  terraform apply -lock=false --auto-approve
    infra-destroy:
        name: Destroy workers infrastructure
        if: startsWith(github.event.head_commit.message, '(workers-down)')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

              # Setup de CLI de Terraform
            - name: Terraform setup
              uses: hashicorp/setup-terraform@v2

              # Crea el cluster en la nube.
            - name: Terraform init
              working-directory: terraform
              env:
                  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
              run: |
                  echo '${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}' > credentials.json

                  ls -lah

                  BUCKET_NAME="terraform_state_cloud"
                  PREFIX="workers/state"

                  terraform init --reconfigure \
                    --backend-config "bucket=${BUCKET_NAME}" \
                    --backend-config "prefix=${PREFIX}"

                  terraform destroy -lock=false --auto-approve
